import swaggerJsDoc from 'swagger-jsdoc'

const options = {
  swaggerDefinition: {
    info: {
      title: 'Mutual Fund API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc',
    },
  },
  apis: ['../routers/*.ts'],
}

const specs = swaggerJsDoc(options)

export default specs
